# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("accessibility.browsewithcaret_shortcut.enabled", false);
user_pref("accessibility.tabfocus", 3);
user_pref("accessibility.typeaheadfind.enablesound", false);
user_pref("accessibility.typeaheadfind.linksonly", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1316215530);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1316215650);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1316280570);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 171118);
user_pref("browser.chrome.toolbar_style", 0);
user_pref("browser.download.manager.behavior", 1);
user_pref("browser.download.manager.focusWhenStarting", true);
user_pref("browser.download.manager.retention", 0);
user_pref("browser.download.manager.showAlertOnComplete", false);
user_pref("browser.enable_automatic_image_resizing", true);
user_pref("browser.fixup.alternate.enabled", false);
user_pref("browser.formfill.enable", false);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.rights.1.shown", true);
user_pref("browser.startup.homepage", "https://encrypted.google.com/");
user_pref("browser.startup.homepage_override.mstone", "rv:6.0.2");
user_pref("browser.tabs.insertRelatedAfterCurrent", false);
user_pref("browser.tabs.loadGroup", 0);
user_pref("browser.zoom.full", false);
user_pref("dom.disable_window_status_change", true);
user_pref("dom.event.contextmenu.enabled", false);
user_pref("extensions.blocklist.pingCountTotal", 8);
user_pref("extensions.blocklist.pingCountVersion", 8);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 4);
user_pref("extensions.enabledAddons", "{59c81df5-4b7a-477b-912d-4e0fdf64e5f2}:0.9.87,{f13b157f-b174-47e7-a34d-4815ddfdfeb8}:0.9.88.2,inspector@mozilla.org:2.0.10,{972ce4c6-7e08-4474-a285-3208198ce6fd}:2.3.3");
user_pref("extensions.getAddons.cache.enabled", false);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"modern@themes.mozilla.org\":{\"descriptor\":\"/usr/lib/seamonkey-2.3.3/extensions/modern@themes.mozilla.org.xpi\",\"mtime\":1315352118000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/seamonkey-2.3.3/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"mtime\":1315352118000}}},{\"name\":\"app-profile\",\"addons\":{\"inspector@mozilla.org\":{\"descriptor\":\"/tmp/h/.mozilla/seamonkey/8j7twz7j.default/extensions/inspector@mozilla.org.xpi\",\"mtime\":1315610610000},\"{f13b157f-b174-47e7-a34d-4815ddfdfeb8}\":{\"descriptor\":\"/tmp/h/.mozilla/seamonkey/8j7twz7j.default/extensions/{f13b157f-b174-47e7-a34d-4815ddfdfeb8}.xpi\",\"mtime\":1315610610000},\"{59c81df5-4b7a-477b-912d-4e0fdf64e5f2}\":{\"descriptor\":\"/tmp/h/.mozilla/seamonkey/8j7twz7j.default/extensions/{59c81df5-4b7a-477b-912d-4e0fdf64e5f2}.xpi\",\"mtime\":1315610610000}}}]");
user_pref("extensions.installedDistroAddon.inspector@mozilla.org", true);
user_pref("extensions.installedDistroAddon.{59c81df5-4b7a-477b-912d-4e0fdf64e5f2}", true);
user_pref("extensions.installedDistroAddon.{f13b157f-b174-47e7-a34d-4815ddfdfeb8}", true);
user_pref("extensions.lastAppVersion", "2.3.3");
user_pref("extensions.lastPlatformVersion", "6.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("general.smoothScroll", true);
user_pref("gfx.blacklist.direct2d", 3);
user_pref("gfx.blacklist.layers.direct3d10", 3);
user_pref("gfx.blacklist.layers.direct3d10-1", 3);
user_pref("gfx.blacklist.layers.direct3d9", 3);
user_pref("gfx.blacklist.layers.opengl", 3);
user_pref("gfx.blacklist.webgl.angle", 3);
user_pref("gfx.blacklist.webgl.opengl", 3);
user_pref("idle.lastDailyNotification", 1316221789);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.lifetimePolicy", 2);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.prefetch-next", false);
user_pref("network.proxy.share_proxy_settings", true);
user_pref("places.database.lastMaintenance", 1316221789);
user_pref("places.history.enabled", false);
user_pref("places.history.expiration.transient_current_max_pages", 114682);
user_pref("pref.downloads.disable_button.edit_actions", false);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.item.cookies", true);
user_pref("privacy.item.offlineApps", true);
user_pref("privacy.item.passwords", true);
user_pref("privacy.popups.remove_blacklist", false);
user_pref("privacy.popups.showBrowserMessage", false);
user_pref("privacy.sanitize.didShutdownSanitize", true);
user_pref("privacy.sanitize.promptOnSanitize", false);
user_pref("privacy.sanitize.sanitizeOnShutdown", true);
user_pref("security.warn_viewing_mixed", false);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.migrated", true);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.rememberSignons", false);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1315611660);
user_pref("toolkit.zoomManager.zoomValues", "0.5,0.75,0.9,1,1.2,1.5,2");
user_pref("xpinstall.enabled", false);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
