# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1315610730);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1315610730);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1315610730);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 173091);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.rights.1.shown", true);
user_pref("browser.startup.homepage", "https://encrypted.google.com/");
user_pref("browser.startup.homepage_override.mstone", "rv:6.0.2");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 4);
user_pref("extensions.enabledAddons", "{59c81df5-4b7a-477b-912d-4e0fdf64e5f2}:0.9.87,{f13b157f-b174-47e7-a34d-4815ddfdfeb8}:0.9.88.2,inspector@mozilla.org:2.0.10,{972ce4c6-7e08-4474-a285-3208198ce6fd}:2.3.3");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"modern@themes.mozilla.org\":{\"descriptor\":\"/usr/lib/seamonkey-2.3.3/extensions/modern@themes.mozilla.org.xpi\",\"mtime\":1315352118000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/seamonkey-2.3.3/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"mtime\":1315352118000}}},{\"name\":\"app-profile\",\"addons\":{\"{59c81df5-4b7a-477b-912d-4e0fdf64e5f2}\":{\"descriptor\":\"/tmp/h/.mozilla/seamonkey/8j7twz7j.default/extensions/{59c81df5-4b7a-477b-912d-4e0fdf64e5f2}.xpi\",\"mtime\":1315610610000},\"{f13b157f-b174-47e7-a34d-4815ddfdfeb8}\":{\"descriptor\":\"/tmp/h/.mozilla/seamonkey/8j7twz7j.default/extensions/{f13b157f-b174-47e7-a34d-4815ddfdfeb8}.xpi\",\"mtime\":1315610610000},\"inspector@mozilla.org\":{\"descriptor\":\"/tmp/h/.mozilla/seamonkey/8j7twz7j.default/extensions/inspector@mozilla.org.xpi\",\"mtime\":1315610610000}}}]");
user_pref("extensions.installedDistroAddon.inspector@mozilla.org", true);
user_pref("extensions.installedDistroAddon.{59c81df5-4b7a-477b-912d-4e0fdf64e5f2}", true);
user_pref("extensions.installedDistroAddon.{f13b157f-b174-47e7-a34d-4815ddfdfeb8}", true);
user_pref("extensions.lastAppVersion", "2.3.3");
user_pref("extensions.lastPlatformVersion", "6.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 114682);
user_pref("toolkit.zoomManager.zoomValues", "0.5,0.75,0.9,1,1.2,1.5,2");
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
